### ISSUE TITLE
Unexpected end of file when using web page method.

### ISSUE THREAD

**Issue by djeraseit** [khoaofgod/phpfastcache#103]
Maybe I downloaded broken code from git 2 hours ago, or maybe it's just me.

I cant for the life of me cache an entire webpage? I get unexpected end of file on cache_start.php.

When I try not splitting the files, I get an error about failed to include phpfastcache/...drivers/...nameofmyphpfile.php.

Im following the cache full webpage example and using file_get_contents (with http) to get my rendered html.

**Comment by khoaofgod** [comment]
@djeraseit  can you copy your error code and paste here.
