### ISSUE TITLE
Way to get configured instance

### ISSUE THREAD

**Issue by harpreetsb** [khoaofgod/phpfastcache#104]
I have slim framework setup.
I wanted to know if I could do.
```php
$fastCache = phpFastCache("files", array("htaccess"      => true,"path"      =>  "cache","securityKey"   =>  "auto"));
```
In index file and do
```php
$fastCache = phpFastCache->getInstance()
```
in the controller to use this further.

Please let me know.

**Comment by khoaofgod** [comment]
$fastCache = phpFastCache() <-- this one is existing Instance already.
You can declare a static class
class mycache {
        public static $cache = array();
}
mycache::$cache['my_cache_name'] = phpFastCache(whatever);

In your function, class, do call:
$fastCache = mycache::$cache['my_cache_name'] ;
