### ISSUE TITLE
Configuring for apc

### ISSUE THREAD

**Issue by nabab** [khoaofgod/phpfastcache#109]
Hi,

I don't understand why your class keeps using getAutoClass when I set the storage to apc. 

  phpFastCache::setup("storage","apc");
  $cacher = phpFastCache('apc');

Whatever I do the config is set to "files". 
  extension_loaded('apc') && ini_get('apc.enabled') both return true

Apache is run through FCGI and strpos(PHP_SAPI,"CGI") returns false.

PHP version is 5.5. Any idea?

**Comment by khoaofgod** [comment]
I take a look tonight

**Comment by nabab** [comment]
Hi there, thanks, but did you have a chance to have a look?
Cheers!

**Comment by nabab** [comment]
Apologies for this: although all the right PHP variables showed up about APC, it wasn't working because the ini file for the module was called twice. Your app did good by selecting the default engine.

**Comment by khoaofgod** [comment]
ok, glad to heard about it.
