### ISSUE TITLE
Warning: Illegal string offset 'value'

### ISSUE THREAD

**Issue by bfintal** [khoaofgod/phpfastcache#112]
I encountered this:

    Warning: Illegal string offset 'value' in phpfastcache/3.0.0/abstract.php on line 61

**Comment by khoaofgod** [comment]
can you guy us more details ?

**Comment by bfintal** [comment]
I just encountered it one time, although haven't encountered it again, so I don't know the reason why the warning appeared. But it shouldn't be too hard to patch against this :)

**Comment by khoaofgod** [comment]
can you tell me which Cache Driver you using? Files or Memcached or something ? for I patch to that driver.

**Comment by bfintal** [comment]
The same error just showed up again. Although a page refresh made it go away. It's really weird and hard to pinpoint.

I'm using both Memcached and Files. I'm building a caching plugin so all drivers would be used.

**Comment by bfintal** [comment]
How about this for the fix @ line 61 in `phpfastcache/3.0.0/abstract.php`:

    $value = isset( $object['value'] ) ? $object['value'] : null;
    return isset($option['all_keys']) && $option['all_keys'] ? $object : $value;

**Comment by khoaofgod** [comment]
hi, can you make a push request for it, I will accept it.

**Comment by bfintal** [comment]
Thanks
