### ISSUE TITLE
Storage `auto` not working correctly

### ISSUE THREAD

**Issue by bfintal** [khoaofgod/phpfastcache#114]
I have my memcache installed and verified working. I have this as my setup:

	$config = array(
		"storage" => 'auto',
		"fallback" => "files",

		"securityKey" => "auto",
		"htaccess" => true,
		"path" => "",

		"memcache" => array(
			array( "127.0.0.1", 11211, 1 ),
		),

		"redis" => array(
			"host" => "127.0.0.1",
			"port" => "",
			"password" => "",
			"database" => "",
			"timeout" => ""
		),
	);
			
	phpFastCache::setup( $config );

It's pretty typical. I have *storage* set to `auto` in the config. If I create an instance specifying `memcache` and display the stats, I get the memcache looking stats:

	$this->cacher = phpFastCache( 'memcache' );
	var_dump( $this->cacher->stats() );

I get:

	array(3) {
	  ["info"]=>
	  string(0) ""
	  ["size"]=>
	  string(0) ""
	  ["data"]=>
	  array(48) {
	    ["pid"]=>
	    string(4) "1124"
	    ["uptime"]=>
	    string(6) "925432"
	    ["time"]=>
	    string(10) "1437900874"
	    ["version"]=>
	    string(15) "1.4.14 (Ubuntu)"
	    ["libevent"]=>
	    string(13) "2.0.21-stable"
	    ["pointer_size"]=>
	    string(2) "64"
	    ["rusage_user"]=>
	    string(9) "32.290035"
	    ["rusage_system"]=>
	    string(9) "19.362574"
	    ["curr_connections"]=>
	    string(1) "9"
	    ["total_connections"]=>
	    string(2) "16"
	    ["connection_structures"]=>
	    string(2) "12"
	    ["reserved_fds"]=>
	    string(2) "20"
	    ["cmd_get"]=>
	    string(5) "50179"
	    ["cmd_set"]=>
	    string(4) "1538"
	    ["cmd_flush"]=>
	    string(2) "24"
	    ["cmd_touch"]=>
	    string(1) "0"
	    ["get_hits"]=>
	    string(5) "48859"
	    ["get_misses"]=>
	    string(4) "1320"
	    ["delete_misses"]=>
	    string(2) "80"
	    ["delete_hits"]=>
	    string(1) "9"
	    ["incr_misses"]=>
	    string(1) "0"
	    ["incr_hits"]=>
	    string(1) "0"
	    ["decr_misses"]=>
	    string(1) "0"
	    ["decr_hits"]=>
	    string(1) "0"
	    ["cas_misses"]=>
	    string(1) "0"
	    ["cas_hits"]=>
	    string(1) "0"
	    ["cas_badval"]=>
	    string(1) "0"
	    ["touch_hits"]=>
	    string(1) "0"
	    ["touch_misses"]=>
	    string(1) "0"
	    ["auth_cmds"]=>
	    string(1) "0"
	    ["auth_errors"]=>
	    string(1) "0"
	    ["bytes_read"]=>
	    string(7) "2816351"
	    ["bytes_written"]=>
	    string(9) "592561055"
	    ["limit_maxbytes"]=>
	    string(9) "134217728"
	    ["accepting_conns"]=>
	    string(1) "1"
	    ["listen_disabled_num"]=>
	    string(1) "0"
	    ["threads"]=>
	    string(1) "4"
	    ["conn_yields"]=>
	    string(1) "0"
	    ["hash_power_level"]=>
	    string(2) "16"
	    ["hash_bytes"]=>
	    string(6) "524288"
	    ["hash_is_expanding"]=>
	    string(1) "0"
	    ["expired_unfetched"]=>
	    string(3) "555"
	    ["evicted_unfetched"]=>
	    string(1) "0"
	    ["bytes"]=>
	    string(6) "179327"
	    ["curr_items"]=>
	    string(3) "171"
	    ["total_items"]=>
	    string(4) "1538"
	    ["evictions"]=>
	    string(1) "0"
	    ["reclaimed"]=>
	    string(3) "749"
	  }
	}

So this verifies that my memcache is working fine. If I create an instance using `files`:

	$this->cacher = phpFastCache( 'files' );
	var_dump( $this->cacher->stats() );

I get:

	array(3) {
	  ["info"]=>
	  array(3) {
	    ["Total"]=>
	    int(307959)
	    ["Removed"]=>
	    int(0)
	    ["Current"]=>
	    int(307959)
	  }
	  ["size"]=>
	  int(307959)
	  ["data"]=>
	  string(0) ""
	}

So the stats of memcache & files are different. But if I do an `auto` or leave it blank:

	$this->cacher = phpFastCache();
	var_dump( $this->cacher->stats() );

I just get:

	array(3) {
	  ["info"]=>
	  array(3) {
	    ["Total"]=>
	    int(186607)
	    ["Removed"]=>
	    int(0)
	    ["Current"]=>
	    int(186607)
	  }
	  ["size"]=>
	  int(186607)
	  ["data"]=>
	  string(0) ""
	}

Which is the same stats when I use `files`. Either I'm using it wrong, or maybe the autodetect isn't working in the master build.

**Comment by khoaofgod** [comment]
basicly, the stats function only work for files I think, for memcache , I don't think I finish it. ^_^
