### ISSUE TITLE
Error when using uninstalled driver

### ISSUE THREAD

**Issue by bfintal** [khoaofgod/phpfastcache#115]
From what I understand, the fallback configuration (e.g. files) should kick in if the current driver being used isn't available.

In my setup I have Redis defined in the configuration as well as a `fallback` to `files`. The Redis module isn't installed in PHP.

When doing a `phpFastCache( 'redis' );` and performing normal cache functions, I get this:

    Fatal error:  Call to a member function connect() on a non-object in /srv/www/wordpress-default/wp-content/combinator-lib/phpfastcache/phpfastcache/3.0.0/drivers/redis.php on line 77

Shouldn't it switch to the fallback instead of throwing the error?

**Comment by khoaofgod** [comment]
fallback was removed from my last committed, since we can't keep check the function connect and then fallback, it make the server / hosting slow when keep connect to redis.

**Comment by bfintal** [comment]
The docs need updating then :P

..And why not just add an if statement in `phpfastcache.php`? I'm going to use this from my end

	if ( class_exists( 'Redis' ) ) {
		$this->cacher = phpFastCache( 'redis' );
	} else if ( class_exists( 'Memcache' ) ) {
		$this->cacher = phpFastCache( 'memcache' );
	} else if ( class_exists( 'Memcached' ) ) {
		$this->cacher = phpFastCache( 'memcached' );
	} else if ( extension_loaded( 'apc' ) && ini_get( 'apc.enabled' ) ) {
		$this->cacher = phpFastCache( 'apc' );
	} else if ( function_exists( "wincache_ucache_set" ) ) {
		$this->cacher = phpFastCache( 'wincache' );
	} else if ( function_exists( "xcache_get" ) {
		$this->cacher = phpFastCache( 'xcache' );
	} else {
		$this->cacher = phpFastCache( 'files' );
	}

**Comment by khoaofgod** [comment]
Yeah, you can just custom it on your config or whatever php, and then do like that if statement.
Anyway, last 3 months I was busy like hell, and didn't fix some bugs, if you can help fix it, just make a commiit and I will accept it on github.
