### ISSUE TITLE
Suggestions to use on multiple servers

### ISSUE THREAD

**Issue by SikiFn** [khoaofgod/phpfastcache#123]
Hello,

Let's say that I have a website running on two servers (the same database and files are replicated on both servers).. I want to use the phpfastcache, but when I want to delete a cache which has a key of "main_page" for example, I want it to be deleted on both server (Knowing that on both servers we already have a cached object with key main_page for example)

what is the best scenario to achieve the above approach without having to propagate to each server and delete the cache manually?

**Comment by khoaofgod** [comment]
Yes, use phpFastCache with "memcache" "memcached" "redis" 
The sync on multiple server, but make sure your servers are same on a datacenter and a private network for fastest speed.
