### ISSUE TITLE
Automating caching with a CRON job

### ISSUE THREAD

**Issue by pesaru** [khoaofgod/phpfastcache#126]
Is it possible to have a CRON job automatically set the cache? Right now, my cache is only working whenever someone actually visits the page. However, I would like the CRON job that runs once a minute to automatically set it. It runs fine and without errors, but doesn't affect load times at all. I'm wondering if the files are being saved to a different directory when executed via the cache (the page people visit is different from the batch file, although they are both caching the output of the same function. I am using "files" as a caching system.

**Comment by mipapo** [comment]
Just set an exact path for the cache in your script: https://github.com/khoaofgod/phpfastcache/wiki/5.1-Custom-Path-to-Files
Usually their will be a folder created with the hostname, which was requested. Your cron is running locally. I think you just calling the script and not make an http request?

**Comment by khoaofgod** [comment]
OK, I will make a file to clean cache with cron.

**Comment by khoaofgod** [comment]
on schedule working now

**Comment by pesaru** [comment]
I figured out what I was doing wrong today. There were two issues. 

When you schedule with a CRON job and you have to set BOTH "path" AND "securityKey." If you do not set path, it will default to a different working directory. If you do not set security key, the live version of the site will create a folder called "yoursitenamecom" but the CRON job will create a folder called "Default."

**Comment by khoaofgod** [comment]
I see,
I will make a cron.php to clean up all the folders. 
And you guys only need to setup 15 mins cron time for cron.php

**Comment by Geolim4** [comment]
We could make this, but there's a lot of enhancements/fixes before.
You can also define your own cron that point to a file that run the `clean()` method API.
I close this one for now, this will be "maybe" discussed in v5.
