### ISSUE TITLE
I will be back from next week.

### ISSUE THREAD

**Issue by khoaofgod** [khoaofgod/phpfastcache#127]
Finally, I finished my projects from last chrismas for Inhouse, Inc,
Next week, I will be back to handle all plans & upgrade the next version of phpfastcache.

Thanks for keep using it, and special thanks to some of you guys, who keep send Pull Requests and update the PhpFastCache for us from last year.

**Comment by reno1979** [comment]
Muaaah! :)

**Comment by bfintal** [comment]
Awesome news, we are in the testing phase for our caching plugin for WordPress called Gambit Cache. We are having problems during our testing, more specifically towards the filesystem caching. Appreciate help on that one.

**Comment by khoaofgod** [comment]
yeah, i'm starting working on some issues now. Any questions just open new issues.

**Comment by bfintal** [comment]
Any updates?
