### ISSUE TITLE
cloudant.com

### ISSUE THREAD

**Issue by sarahansen223h** [khoaofgod/phpfastcache#131]
Hi,

- I want to say this is a really good cache lib! i hope many people use it and you get very known. What i'm missing personal is a way to use cloudant.com with phpfastcache. I hope you can support cloudant.com

**Comment by Geolim4** [comment]
We do not have plan for third party drivers right now, it's not a "final no", but we have a lot things to fix and improve currently ;)

Regards,
Georges
