### ISSUE TITLE
clean expired cache

### ISSUE THREAD

**Issue by xtix** [khoaofgod/phpfastcache#142]
I use "files" cache. Often part of caching data is expired and nobody uses them long time. Data occupies much space (several gigabytes and more). I would like to clear only expired cache (for example by cron), because operation get data is very slow. I need a function cleanExpiredCache() or something like this.

**Comment by synyalex** [comment]
With this handle $ cache-> stats (); Scheduled for example cron, though with a large volume of cache error TIMEOUT

**Comment by khoaofgod** [comment]
If anyone work on this, I will happy.
If not, wait until Next month, right now company is so busy.

**Comment by synyalex** [comment]
I have exceeded the file cache and 1 GB of regular means Clear impossible on a shared hosting there is an overload and usually a timeout.
I decided to add a feature scheduled cron to the desired period of time is called and clears the cache for a folder in the rotation.
The problem has disappeared, the limits in order
in abstract.php
<code>function rotate($option = array()) {
        return $this->rotate_clean($option);
    }
</code>
in files.php
<code> 

    function rotate_clean($option = array()) {
        $res = array(
            "info"  =>  "",
            "size"  =>  "",
            "count" =>  "",           
        );
        $path = $this->getPath();
        $total = 0;
        $removed = 0;
        $files=glob($path.'/*',GLOB_ONLYDIR);
        if (!$counter = @file_get_contents($path."/counter.txt")) $counter=0;
        $counter++; $counters=count($files);
		if ($counter>=$counters ) $counter=0;
		@file_put_contents($path."/counter.txt",$counter);
		$file=$files[$counter]; 
		
            if($file!="." && $file!=".." && is_dir($file)) { //if?
            
                $subdir = @opendir($file);
                if(!$subdir) {
                    throw new Exception("Can't read path:".$path."/".$file,93);
                }

                while(false !==($f = @readdir($subdir))) {
                    if($f!="." && $f!="..") {
                        $file_path = $file."/".$f;
                        $size = @filesize($file_path);
                        $object = $this->decode($this->readfile($file_path));
                        if($this->isExpired($object)) {
                            @unlink($file_path);
                            $removed += $size; 
                        }
                        $total += $size;
                    }
                } 
            } // end if
  

       $res['size'] = $total - $removed;
       $res['info'] = array(
                "Total [bytes]" => $total,
                "Expired and removed [bytes]" => $removed,
                "Current [bytes]" => $res['size'],
               
       );
       $res['count'] = array(
				"Total" => $counters,
				"Current position" => $counter,
        );
       
       return $res;
    }
</code>

call
<code>
include_once($_SERVER['DOCUMENT_ROOT']."phpfastcache.php");
$cache = phpFastCache(); 
$array = $cache->rotate(); 
print_r($array); 
</code>

**Comment by khoaofgod** [comment]
hi bro, can you comit a request, and document for this method. I will accept the merge to help others right away.

**Comment by xtix** [comment]
thx for help, i hope this will be added to the release.

**Comment by khoaofgod** [comment]
released
