### ISSUE TITLE
Sqlite configuration

### ISSUE THREAD

**Issue by darkoromanov** [khoaofgod/phpfastcache#143]
Hi,

I don't know where to ask, so forgive me if I open an issue. I can't find an example or documentation about how to configure Sqlite. Google was not useful this time.

**Comment by fbonzon** [comment]
I was able to configure sqlite like this:

```php
require_once '/path/to/phpfastcache.php';
phpFastCache::setup('path', '/path/to/phpfastcache');
$cache = phpFastCache('sqlite');
```

On first two lines, you need to change the paths to your setup:
- On line 1, it's the root folder of the phpfastcache source code.
- On line 2, it's the root folder where caching files will be stored. It must be writeable  by the UNIX user that your webserver runs with, and preferably located outside the web root, so it is not directly accessible from the web.

**Comment by darkoromanov** [comment]
Thanks, it works now. I was using an old version of phpFastCache so your syntax was not recognized at first, I updated and now it works and I see it correctly creates the database file.
