### ISSUE TITLE
[Predis] Issue with DELETE command

### ISSUE THREAD

**Issue by stormoPL** [khoaofgod/phpfastcache#144]
I have faced an issue when trying to delete key using $cache->delete("key_name"). I works with auto storage but when switching to Predis it fails with error informing that "delete" is not valid command for Predis.

I traced it back to line 124 in Predis driver where "DELETE" instead of proper Redis "DEL" is passed.
 
https://github.com/khoaofgod/phpfastcache/blob/final/phpfastcache/3.0.0/drivers/predis.php#L124

Changing:

$this->instant->**delete**($keyword);

for:

$this->instant->**del**($keyword);

solves the problem.

**Comment by khoaofgod** [comment]
Can you comit the change? I will accept it. Make sure Predis and Redis is 2 different.
