### ISSUE TITLE
Could phpfastcache handle using api like this?

### ISSUE THREAD

**Issue by ninanurcahyani** [khoaofgod/phpfastcache#145]
could handle this 

if (isset($_GET['searchby'])) { $searchby = strip_tags($_GET['searchby']); }
$searchby = str_replace(array('title', 'author', 'publisher', 'isbn', 'categories'), array('intitle:', 'inauthor:', 'inpublisher:', 'isbn:', 'subject:'), $searchby);
$search = strip_tags($_GET['search']);
$search = str_replace('-', ' ', $search);
$search = preg_replace('/\s[\s]+/', ' ', $search);  // Strip off multiple spaces
$search = str_replace(' ', '-', $search);
$search = preg_replace('/^[\-]+/','',$search); // Strip off the starting hyphens
$search = preg_replace('/[\-]+$/','',$search); // // Strip off the ending hyphens
$search = str_replace('-', '+', $search);
$o = 0;
$p=1;
$p++;
if ($p==1) { $hasil = 0; } else { $hasil = ($p*10)-9; }
$apikey=array(YTAPI01, YTAPI02, YTAPI03, YTAPI04, YTAPI05, YTAPI06, YTAPI07, YTAPI08, YTAPI09, YTAPI10);
$random_keys=array_rand($apikey,1);

$html = file_get_contents("https://www.googleapis.com/books/v1/volumes?q=".$searchby."".$search."&maxResults=".SEARCHRESULT."&key=".$apikey[$random_keys]."&startIndex=0");
$youtube = json_decode($html, true);
$totalItems = $youtube['totalItems'];

please help me for cache $html, and there is dynamic in api url, can i get them all using phpfastcache? thanks

**Comment by fbonzon** [comment]
Please format, indent, etc. your code nicely in a PHP code block using Markdown, so it's easier to read for others who want to help.

Yes, phpfastcache can help you here. Caching API replies is a typical use case. I would use the `sqlite` engine, and cache for 24 hours.
