### ISSUE TITLE
Predis class required even it is already there

### ISSUE THREAD

**Issue by vincent** [khoaofgod/phpfastcache#146]
The driver class [loads its own Predis class file](https://github.com/khoaofgod/phpfastcache/blob/5ee8aadcf04921f1b6f5742d2610973a5d8e9fe0/phpfastcache/3.0.0/abstract.php#L268) but this is problematic when Predis is already loaded, and it will fail with "Cannot redeclare class Predis\Autoloader"

I'm not sure sure how you want to resolve this, but if you have some thoughts about it I can make a PR.

**Comment by khoaofgod** [comment]
redeclare, mean somehow you required the autoloader before phpFastCache already.
Before I make a change for it, you can do like this:
Go to: drivers/predis.php
Look for: $this->required_extension("predis-1.0/autoload.php");
Comment // these lines and I think you will be all set.

I will try to check if Predis loaded on next version, right now I am still busy, if someone comite the code, I will thankful and merge it rightaway.

**Comment by vincent** [comment]
yep, thats the workaround I used.

I'll try to find some time to make a PR.

thanks
