### ISSUE TITLE
Share cache between 2 projects in same server.

### ISSUE THREAD

**Issue by ricardodavidsoares** [khoaofgod/phpfastcache#154]
Hi,
I'm having this problem and don't know how to solve it. I have two web applications runing in same server but with diferent domain names, so, when I use PHPFastCache each one creates it's own folder on the specified cache path.
What I want is to make them share the cache folder, so when one puts info into cache the other can read it.
Can you please help me?

Thank you in advance.

**Comment by remowashere** [comment]
I assume you are using something like;
$keyword_webpage = md5($_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].$_SERVER['QUERY_STRING']);

There's no need to do this, you can setup both domains to use /tmp/ as caching dir.

**Comment by ricardodavidsoares** [comment]
No. I'm doing just "$cache = phpFastCache();" and then "$cache->set('xpto', $arr_dados, $this->ttl);" "$data = $cache->get('xpto')".
I didn't change any default config, but I can see two folder, one for each domain, in /tmp/.

**Comment by ricardodavidsoares** [comment]
Hii,
I just found my solution here "http://stackoverflow.com/questions/33805633/how-to-clear-phpfastcache-when-path-set-to-tmp". Thank you for your time either way.

Greetings.

**Comment by ricardodavidsoares** [comment]
I downloaded the latest version today and the solution I used doesn't solve the issue anymore.
Now, when I set the path it appends a "-" to it. For example, if I set it to "XPTO" the folder created will be "XPTO-".
I don't know why and I'm stuck with this problem. Would appreciate a help. Thank you.

**Comment by mipapo** [comment]
Yep - Same problem here. Havn't found it on the quick way. Has to be a bug since one of the latest releases

**Comment by Geolim4** [comment]
Just define a shared directory for the cache and a shared securityKey, it should work.
Anyway please test the last release (4.0.3), it is not production stable, but stable enough for testing purposes. Reopen this issue if needed.
