### ISSUE TITLE
Wrong config for REDIS driver

### ISSUE THREAD

**Issue by drAlberT** [khoaofgod/phpfastcache#157]
Hi,
  there should be something strange in the handling of the phpFastCache() function parameters/defaults config .. the following code doesn't works for **redis**, while it works perfectly for **memcache** 

```php
<?php

require __DIR__.'/../vendor/autoload.php';

define('_CACHE_EXPIRE_TIME', 60 * 60 * 24);

$cache = phpFastCache('redis');

$page_hash = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].$_SERVER['QUERY_STRING'].serialize($_COOKIE);
$html = $cache->get($page_hash);
if (null !== $html) {
    exit($html); // output the cached page
}

ob_start();
require __DIR__.'/index.php';  // generate the page
$html = ob_get_flush();           // and serve it soon

// now save it in the cache
$cache->set($page_hash, $html, _CACHE_EXPIRE_TIME);
```

**Redis is correctly installed and working, as telnetting I can connect**

This is the PHP error given:
```
PHP Fatal error:  Call to a member function connect() on null in /var/www/sites/XXX/vendor/phpfastcache/phpfastcache/phpfastcache/3.0.0/drivers/redis.php on line 78
```

**Comment by khoaofgod** [comment]
do you install redis for php? look like php don't have redis lib.

**Comment by khoaofgod** [comment]
if your PHP version don't have Redis Lib, just use "Predis" built-in in PHP Fastcache.

**Comment by drAlberT** [comment]
Uhmmmm will double check, tnx
Il 18/dic/2015 19:42, "Khoa Bui" <notifications@github.com> ha scritto:

**Comment by khoaofgod** [comment]
@drAlberT  : $cache = phpFastCache('redis'); 
try $cache = phpFastCache('predis'); <-- this one will use built-in Predis

**Comment by drAlberT** [comment]
@khoaofgod ok, it was my bad .. missing extension loaded

This issue became an RFE then :P .. please handle missing drivers errors more descriptively :)

Thank you
