### ISSUE TITLE
Cache API called by shortcode

### ISSUE THREAD

**Issue by ZioProg** [khoaofgod/phpfastcache#159]
Hi there

I use a shortcode to make product search with Amazon API. The attrs of the shortcode is the keyword I put in the ItemSearch.
Here you are my code:

```php
function best_price_shortcode($attrs)
        {
		$kw = $attrs['kw'];
		
// get from cache
$product_info = __c()->$kw;

if($product_info == null) {
    $product_info = get_amazon_lowest_price_product( $kw );	;
    // write to cache;
    __c()->$kw = array($product_info, 3600);
}

[...]

```

However, it is "working" but without caching.  What I would like to do is to cache differently each keyword ($kw) inserted with the shortcode and get returned info from cache after the first call for one hour.

Could someone help me on this?

Thanks

**Comment by Geolim4** [comment]
You have to call the API method such as `get()` and `set()`.
The latest version documents this ;)
