### ISSUE TITLE
Support for Sharedance

### ISSUE THREAD

**Issue by dearteno** [khoaofgod/phpfastcache#160]
I try to implement the Sharedance Extension that use  your ssdb's extension as code  base but do not success.
please  support for  Sharedance Cache.
About Sharedance : http://www.phpclasses.org/package/3712-PHP-Access-Sharedance-distributed-cache-servers.html

**Comment by Geolim4** [comment]
It's not planned right now, but feel free to contribute when you'll get some more skills, i'll be glad to merge a new driver to Pfc ;)
