### ISSUE TITLE
DeleteMulti() is not working properly (Not as defined in readme)

### ISSUE THREAD

**Issue by Geolim4** [khoaofgod/phpfastcache#175]
Hi,

in the readme, you wrote this sample:
> $cache->deleteMulti(array("key1","key2","key3"));
But when checking *deleteMulti()* method here: https://github.com/khoaofgod/phpfastcache/blob/final/phpfastcache/3.0.0/abstract.php#L178

You loop on keyword, perfect, but why deleting **$array[0]** in the reference ?
It's same thing than:
> $cache->deleting('k');

So **$array[0]** in **$array** will take the first byte as it is a string.

I am surprised that one noticed this before O.o
If you want a PR, just let me know and i'll do it with pleasure :)

Regards,
Georges

**Comment by khoaofgod** [comment]
sure @Geolim4 
Can you do a fix for it, also, remember the one that you disagree with "@read" something, can you remove these "@" too.

Thanks so much.

**Comment by Geolim4** [comment]
In 2 separate PR i guess?

**Comment by Geolim4** [comment]
Done, finally, is two separate commits

**Comment by Geolim4** [comment]
Ok merged, thanks !
