### ISSUE TITLE
Adding phpDoc block comment

### ISSUE THREAD

**Issue by Geolim4** [khoaofgod/phpfastcache#177]
Hi,

I think that we must clean all the dirty/random comments, and follow the [psr-5 fig-standards](https://github.com/phpDocumentor/fig-standards/tree/master/proposed), still in draft but you get the concept.

I principally mention these one:

- @licence
- @method
- @var
- @author
- @package
- @see
- @deprecated

Regards,
Georges

**Comment by Geolim4** [comment]
@khoaofgod Are you ok with this ?

**Comment by khoaofgod** [comment]
@Geolim4 if you can help working on this :dancer:  I will thankful, I was just too busy, so most the bugs right now, I accept the commit from other developers.

**Comment by Geolim4** [comment]
Okey, nice so !!

**Comment by Geolim4** [comment]
What's the php minimum compatibility ?

**Comment by khoaofgod** [comment]
Make it 5.1 @Geolim4 
I think  5.1 is minimum right now and JSON supported on 5,1

**Comment by Geolim4** [comment]
Copy that :)

**Comment by khoaofgod** [comment]
thanks ^_^

**Comment by Geolim4** [comment]
I will also define missing visibility attributes and follow some psr-1/2 recommendations.
Is up to you to validate the PR later :)

**Comment by Geolim4** [comment]
You will have a lot of code review :D

**Comment by khoaofgod** [comment]
sure, ^_^

**Comment by Geolim4** [comment]
Done but i resolved a conflict on some files, can you check if a don't forget anything during the merge ?
Thanks.

    Conflicts:
        phpfastcache/3.0.0/abstract.php
        phpfastcache/3.0.0/drivers/files.php
        phpfastcache/3.0.0/drivers/sqlite.php
        phpfastcache/3.0.0/phpfastcache.php

**Comment by Geolim4** [comment]
Commit @17c589f
