### ISSUE TITLE
Latest version update - error

### ISSUE THREAD

**Issue by dvLden** [khoaofgod/phpfastcache#179]
I am unsure what is it, not sure if the image will help either, but here it is:

<img width="1381" alt="screen shot 2016-02-01 at 01 39 28" src="https://cloud.githubusercontent.com/assets/3460368/12706414/d397e2b4-c884-11e5-8095-11e438eb8ef6.png">

**Comment by khoaofgod** [comment]
@dvLden  can you download and try again, someone made a fix patch this morning already

**Comment by Geolim4** [comment]
Fixed
