### ISSUE TITLE
Custom Exception Class for a better control

### ISSUE THREAD

**Issue by Geolim4** [khoaofgod/phpfastcache#182]
I think that using SPL Exception is a bit "easy" we should make a custom exception to have a better control of the code.

Such as phpfastcacheCoreException and phpfastcacheDriverException, are you ok ?

**Comment by khoaofgod** [comment]
you want to help me make one? if yes then go ahead.. xD

**Comment by Geolim4** [comment]
Then let's go !
I will keep going in your "legacy code" way, until someone make the autoload ;)

**Comment by khoaofgod** [comment]
you know what, I am feel like I out date these day, u guys are just keep better and better. LOL. How about, u create a whole new version, release 4, with that and autoload too :dancer:  
I will share you project permission for you can change the home page with your information in contact, if you help on this..xD my way coding still old way =.=!

**Comment by Geolim4** [comment]
Not needed for now, i'm glad to contribute ;)

**Comment by khoaofgod** [comment]
yeah, then thanks for help me on this.
