### ISSUE TITLE
PDO CHMOD 0777

### ISSUE THREAD

**Issue by saiful** [khoaofgod/phpfastcache#27]
Hallo
I have a issued about pdo cache. 

I created a modul for cron job, in cron job need to create a folder 
cache/f011sdfasddsd8efed7as420323c793/ exampled. In these folder will be consist two files they are :
pdo.caching and config.41065cf4fd8asdf 7d52bedfda24a32adf75b1fe0.cache.ini

And I am considering for chmod it 0777 or Writable permission, I am afraid if some body can download these file via browser. I have test and it can be downloaded.

Other modul I set automatically, other module created cache APC, so I look cron job module and others moduls have created different cache, they are still in one application.

How to set chmod not to 0777 but still created pdo cache.

Thanks

**Comment by nikmauro** [comment]
Here the config 

```PHP
$cms39_cache_config = array(
        "storage"   =>  "apc",
        "path"      =>  ABS_CACHE_PATH , /** /var/www/vhosts/###/httpdocs/tmp/cache/  */
        "htaccess"  =>  false
    );

phpFastCache::setup($cms39_cache_config);
$cache = phpFastCache();
```
The server running FastCGI with PHP 5.4.37

And the script return 

Fatal error: Uncaught exception 'Exception' with message 'PLEASE CHMOD /var/www/vhosts/###/httpdocs/tmp/cache//cache.storage.###/ - 0777 OR ANY WRITABLE PERMISSION!' in /var/www/vhosts/###/httpdocs/vendor/phpfastcache/phpfastcache/phpfastcache/2.4.2/drivers/files.php:58 Stack trace: #0 /var/www/vhosts/###/httpdocs/vendor/phpfastcache/phpfastcache/phpfastcache/2.4.2/drivers/files.php(108): phpfastcache_files->getFilePath('4cf0c74dd903c3b...') #1 /var/www/vhosts/###/httpdocs/vendor/phpfastcache/phpfastcache/phpfastcache/2.4.2/base.php(159): phpfastcache_files->driver_get('4cf0c74dd903c3b...', Array) #2 /var/www/vhosts/###/httpdocs/library/cache.php(151): phpFastCache->get('4cf0c74dd903c3b...') #3 /var/www/vhosts/###/httpdocs/library/functions.php(1385): cms39_cache_fetch('siteurl') #4 /var/www/vhosts/###/httpdocs/library/plugins.php(6): get_option('siteurl') #5 /var/www/vhosts/###/httpdocs/library/settings.php(6): cms39_has_su in /var/www/vhosts/###/httpdocs/vendor/phpfastcache/phpfastcache/phpfastcache/2.4.2/drivers/files.php on line 58

**Comment by khoaofgod** [comment]
i will test fastcgi tonight with ur config and do a hotfix

-----Original Message-----

**Comment by nikmauro** [comment]
The APC driver work with Fast CGI here the my phpinfo

If change the config with this the cache working with APC.

```PHP
$cache = phpFastCache("apc");
```

phpinfo
```
System	Linux  2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64
Build Date	Jan 21 2015 11:11:51
Server API	CGI/FastCGI
Virtual Directory Support	disabled

Configuration
apc
APC Support	enabled
Version	3.1.15-dev
APC Debugging	Disabled
MMAP Support	Enabled
MMAP File Mask	/tmp/apc.cT3Aer
Locking type	pthread mutex Locks
Serialization Support	php, igbinary
Revision	$Revision$
Build Date	Feb 14 2014 13:49:03
```

**Comment by khoaofgod** [comment]
ok, I work on that. I will rewrite the way abstract class work right now on next release Feb 23.
New class will be coded for faster and config much easier.
