### ISSUE TITLE
codehelper.io is down, detect_visitor_location doesn't work

### ISSUE THREAD

**Issue by oitsuki** [khoaofgod/phpfastcache#58]
Hello Khoa,

Phpfastcache with detect_visitor_location does'nt work. codehelper.io is down, Have a delay to fix it or what I can do to resolve this problem ?
Thank you.

Regards

**Comment by Arvey18** [comment]
Hi!

Is codehelper.io still working. what is the new url for the API? please share

**Comment by CarlosJa** [comment]
If anyone is looking for api.codehelper.io  i ended up taking over the project. it's now  Snoopi.io  you can use https://api.snoopi.io/186.83.228.58  as an example
