### ISSUE TITLE
Disable phpfastcache temporarily

### ISSUE THREAD

**Issue by richcom** [khoaofgod/phpfastcache#61]
Hello,

I use your phpfastcache and have a question:

how do I disable phpfastcache temporarily.

many greetings

Richy

**Comment by khoaofgod** [comment]
hahaha.
Next version, I will add this option, nice one, bro!

**Comment by khoaofgod** [comment]
@richcom  will have this option on next version 2.2 next week.

**Comment by khoaofgod** [comment]
Done on release_2.4 release next week.

**Comment by richcom** [comment]
wonderful that you have the implemented as soon!!
