### ISSUE TITLE
End of support of APC for PHP 5.5.x and support of OPcache

### ISSUE THREAD

**Issue by alexboss** [khoaofgod/phpfastcache#65]
Dear phpfastcache developers,

With the announcement of the end of support of APC within PHP 5.5.x and its replacement by OPcache, is there any plan to update the library to support OPcache ?

Thanks a lot and best regards,

Alexandre 8)

**Comment by nicocasel** [comment]
Thanks for posting this issue, we have exactly the same demand.

**Comment by khoaofgod** [comment]
by the end of Jan, PhpFastCache will release version 3.0 that include reddis and OPCache, the old driver APC still avaiable.

Release date will be Jan 31 or Feb 1.

**Comment by alexboss** [comment]
That's excellent news, thank you ! You can be sure that we'll be among the first users! Alexandre 8)

**Comment by khoaofgod** [comment]
i'm working on it.

**Comment by khoaofgod** [comment]
OPCache is not an object caching, it's cache the SCRIPT. Automatic already.
All you need is set OPCache enabled on php.ini 

This is different with APC Cache.

**Comment by ndzou** [comment]
The user cache portion of APC now continues in APCu, Fedora/EPEL package php-pecl-apcu, if you install this you can keep using the apc driver.
