### ISSUE TITLE
Release 2.4.1

### ISSUE THREAD

**Issue by khoaofgod** [khoaofgod/phpfastcache#68]
Release 2.4 will be release on next Monday Feb 02.

What's new
- Redis supported
"pecl install redis"

- Cookie Driver
Fun for who want to store cache on visitor's browser.

- Non-Expring Cache for Object
Example: set("keyword", $data); will be non-expire until you do delete("keyword");

- Temporary Disabled phpFastCache
use: phpFastCache::$disabled = true; 
After this line, all get("keyword") will return NULL;

- Improved Files Cache for Busy Disk
Busy Disk will skip caching object and continue without error_log problems.

- Composers will be added

- Improve fallback
If specific driver that you set is not available then system will use "files" driver

Then March 03 will be release 2.5:
-- Planned for MongoDB
-- External Server Caching
-- and phpFastSQL.com will be release together.

**Comment by tylercollier** [comment]
If Redis isn't installed, and you try to use it, it you will get:

```
PHP Fatal error:  Call to a member function connect() on a non-object in phpfastcache/drivers/redis.php on line 45
```

which is an un-catchable error.

This happens because you have this code in `redis.php __construct()`

```
if(class_exists("Redis")) {
    $this->instant = new Redis();
}
```

If the Redis class doesn't exist, you never assign to `$this->instant`, and thus later, `$this->instant->connect($p1,$p2,$p3)` thows the error.

**Comment by tylercollier** [comment]
PS: It's probably worth mentioning in the README that using Redis requires use of [phpredis](https://github.com/phpredis/phpredis), as opposed to another library such as [predis](https://github.com/nrk/predis).

**Comment by khoaofgod** [comment]
@tylercollier 
+ I will add phpredis on README
+ I will add 1 more driver called "predis" on Monday, Jan 09 for who use predis.
