### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by sv1gzf** [khoaofgod/phpfastcache#70]
I'm trying to download the project with the use of the composer but I always get an error.

I'm using the command:
php composer.phar require "phpfastcache/phpfastcache":*

and I get:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpfastcache/phpfastcache could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Is this method supported ?

**Comment by ndzou** [comment]
Same problem here, putting 

"phpfastcache/phpfastcache": "dev-Release_2.*"

in the composer.json does not work either.

I do see the package listed on packgest.org, but it's source directory appears incorrect.  Perhaps it needs to point to the actual source path on Github?  Like:

https://github.com/khoaofgod/phpfastcache/tree/Release_2.4.1/phpfastcache_2.4/phpfastcache

**Comment by khoaofgod** [comment]
K, i'm working on this. Next release Mon Feb 09 will be fixed

**Comment by khoaofgod** [comment]
https://packagist.org/packages/phpfastcache/phpfastcache

**Comment by sv1gzf** [comment]
The composer is not working properly
Warning: require(....../vendor/phpfastcache/phpfastcache/phpfastcache/phpfastcache/phpfastcache.php): failed to open stream: No such file or directory in ..../vendor/composer/autoload_real.php on line 54

**Comment by khoaofgod** [comment]
Fixed already, try again.
