### ISSUE TITLE
cache empty after calling systemInfo()

### ISSUE THREAD

**Issue by reno1979** [khoaofgod/phpfastcache#74]
V2.4.1
situation: storage: files

After calling systemInfo() (trying to determine the chosen storage system) 
the stats() return empty. That's is the info part of the returned array exists but all values are zero. 

Is the SystemInfo changing a directory or does it call a init/constructor?

**Comment by khoaofgod** [comment]
I take a look tonigth when I get home.

**Comment by reno1979** [comment]
Thank you, that's fast.
