### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by sv1gzf** [khoaofgod/phpfastcache#76]
The composer is not working properly

Warning: require(xxxxxx/vendor/phpfastcache/phpfastcache/phpfastcache/phpfastcache/phpfastcache.php): failed to open stream: No such file or directory in xxxxxx/vendor/composer/autoload_real.php on line 54

It looks like the path is not correct.

**Comment by lichunqiang** [comment]
https://github.com/khoaofgod/phpfastcache/blob/final/composer.json#L20

It seems wrong path there!

**Comment by antoniocambados** [comment]
Just satumbled upon this, I had to manually solve it this _messy_ way:

```php
// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/phpfastcache/phpfastcache/phpfastcache.php',
);
```

**Comment by lichunqiang** [comment]
oh... This is the author's business, but it's a temporary solution :+1:

**Comment by nikmauro** [comment]
composer require "phpfastcache/phpfastcache": "dev-final"
and return this error Warning: 
```PHP
require(/vendor/phpfastcache/phpfastcache/phpfastcache/phpfastcache/phpfastcache.php): failed to open stream: No such file or directory in /home/www/cms39/vendor/composer/autoload_real.php on line 54
```

**Comment by khoaofgod** [comment]
Fixed.

**Comment by khoaofgod** [comment]
@nikmauro @lichunqiang @antoniocambados @sv1gzf 
Can you guys do me a favor, try composer again, and let me know if it work or not.
I am not similar with composer, I just updated the json file, hope it good now.

Plz test and let me know, also, if u have any suggestion on json file, plz comment here, I am not good at composer.

**Comment by nikmauro** [comment]
perfect!
