### ISSUE TITLE
exception with message Can't create .htaccess

### ISSUE THREAD

**Issue by epsi1on** [khoaofgod/phpfastcache#81]
Hello,
I'm getting this exception:
 'Can't create .htaccess' in /home/***/public_html/***/phpfastcache/phpfastcache/2.4.2/base.php:756 Stack trace: #0 
 /home/***/public_html/***/phpfastcache/phpfastcache/2.4.2/base.php(831): phpFastCache->htaccessGen('/home/***/...') #1 /home/***/public_html/***/phpfastcache/phpfastcache/2.4.2/drivers/files.php(25): phpFastCache->getPath() #2 /home/***/public_html/***/phpfastcache/phpfastcache/2.4.2/base.php(536): phpfastcache_files->__construct(Array) #3 /home/***/public_html/***/phpfastcache/phpfastcache/2.4.2/base.php(22): phpFastCache->__construct('memcached', Array) #4 /home/***/public_html/***/jupdate.php(38): phpFastCache('memcached') #5 {main}

**Comment by khoaofgod** [comment]
I test it tonight, can you tell me are u using files  / auto or memcached ?
If u are using memcached, please sure that ur memcached server is right.

And are u use FCGi / suPHP / CGI or PHP as Module ?

**Comment by epsi1on** [comment]
Hi.
this is my code where it throws the exception:

$cache = phpFastCache("memcached"); // <<<<<< this throws the exception
$results = $cache->get('my_key');

How can i find out memcached works fine?

also about last question, actually i do not know what do you mean. I'm not a php guy, i guess i'm just using php!

thank you so much

**Comment by ZiZuu-store** [comment]
Replace memcached with "memcache"
w/o d

Il giovedì 19 febbraio 2015, epsi1on <notifications@github.com> ha scritto:

> Hi.
> this is my code where it throws the exception:
>
> $cache = phpFastCache("memcached"); // <<<<<< this throws the exception
> $results = $cache->get('my_key');
>
> How can i find out memcached works fine?
>
> also about last question, actually i do not know what do you mean. I'm not
> a php guy, i guess i'm just using php!
>
> thank you so much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/khoaofgod/phpfastcache/issues/81#issuecomment-75128244>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by epsi1on** [comment]
with changing memcached with memcache it works but gives a notice:
is everything ok?

<b>Notice</b>:  Memcache::get() [<a href='memcache.get'>memcache.get</a>]: Server 127.0.0.1 (tcp 11211) failed with: Connection refused (111) in <b>/home/<site>/public_html/phpfastcache/phpfastcache/2.4.2/drivers/memcache.php</b> on line <b>82</b><br />

**Comment by ZiZuu-store** [comment]
No it's saying that the memcached process is refusing connection on its
standard port (11211)

Check that memcached is running and accepting connection on localhost

Il giovedì 19 febbraio 2015, epsi1on <notifications@github.com> ha scritto:

> with changing memcached with memcache it works but gives a notice:
> is everything ok?
>
> *Notice*: Memcache::get() [memcache.get]: Server 127.0.0.1 (tcp 11211)
> failed with: Connection refused (111) in
> */home//public_html/phpfastcache/phpfastcache/2.4.2/drivers/memcache.php*
> on line *82*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/khoaofgod/phpfastcache/issues/81#issuecomment-75129604>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by khoaofgod** [comment]
try this one on ur server:
ps -A | grep memcache

Maybe ur memcache services is not running, and that why the Files as backup driver run.
