### ISSUE TITLE
chmod_permission in base.php. would cause wrong permission on created folder.

### ISSUE THREAD

**Issue by MaxLuan** [khoaofgod/phpfastcache#82]
Dear khoaofgod,

I find that sometimes, instead of a 0644 permission, the cache folder is created with a 1204 permission. 

The exception “Sorry, Please create ".$this->option("path")."/".$this->option("securityKey")."/ and SET Mode 0777 or any Writable Permission!” is thrown. 

According to this link, http://php.net/manual/en/function.chmod.php#96086, I changed 
var $chmod_permission = array(
		"default_module"    =>  “0666”,
		"default_cgi"       =>  “0644”,
		"chmod"             =>  “0777”, // set this one to your chmod | blank will use default chmod above
	);
to 
var $chmod_permission = array(
		"default_module"    =>  0666,
		"default_cgi"       =>  0644,
		"chmod"             =>  0777, // set this one to your chmod | blank will use default chmod above
	);
which resolved the problem. 

Would you please look into this ?

**Comment by khoaofgod** [comment]
@MaxLuan I take care this tonight before mid night. Hahhaa. A little bit overload this weekend, since I spent all my time for  Lunar New Year and my gf... >_<

I see what you mean on this, I will change it to numeric tonight and push it together with the new version.

**Comment by MaxLuan** [comment]
@khoaofgod Thanks for the quick response and happy new year. Nice work by the way, the system rocks.

**Comment by clashboy** [comment]
I can confirm the this bug.

**Comment by gcleaves** [comment]
same problem

**Comment by khoaofgod** [comment]
I fixed it yesterday already @gcleaves  @clashboy  can you guys download new version and try again.
Just delete the old folder cache.

**Comment by khoaofgod** [comment]
https://github.com/khoaofgod/phpfastcache/tree/2.4.3
