### ISSUE TITLE
Is composer always updating to 'final' branch?

### ISSUE THREAD

**Issue by marzsman** [khoaofgod/phpfastcache#83]
I moved my application to the composer version of phpfastcache but it looks like the library is updated to the master branch 'final'.

Is it possible to create release branches so we can update to composer.json when changes to the library are tested in our application?

**Comment by ta2edchimp** [comment]
Simply tagging the current branch at its respective stage with something that looks like a version should do it, imo.

According to [this section in the Composer docs](https://getcomposer.org/doc/02-libraries.md#tags), it should be enough to tag the current branch with `2.4.3` on Feb. 23rd (... or whenever it will be finished :P).

**Comment by khoaofgod** [comment]
cool. thanks for the document bro. i will take a look at it and try to comit this one together with new version tonight.

**Comment by khoaofgod** [comment]
https://packagist.org/packages/phpfastcache/phpfastcache

I added tags 2.4.2
next will be 2.4.3

**Comment by marzsman** [comment]
Great, thx for the quick fix!

**Comment by ta2edchimp** [comment]
Yes, thanks A LOT!
