### ISSUE TITLE
Make it Windows compatible (mkdir and unallowed character problem)

### ISSUE THREAD

**Issue by Neui** [khoaofgod/phpfastcache#84]
Ah just forgot to write..
I noticed, this thing doesnt work on windows.
See: https://github.com/khoaofgod/phpfastcache/blob/final/phpfastcache/3.0.0/phpfastcache.php#L180
If printing out $full_path then i will get "[...]/phpfastcaches/localhost:25565/"
The : character is not allowed in Windows, so it does not work.
Maybe this character could be replaced by a + sign. I dont think any domain name includes an + sign.

**Comment by khoaofgod** [comment]
got it

**Comment by khoaofgod** [comment]
@Neui Fixed
