### ISSUE TITLE
Fatal error about example2.php

### ISSUE THREAD

**Issue by lyj289** [khoaofgod/phpfastcache#85]
hello , i am learning the phpfastcache,and i have some problems.

when i run the example2.php,there are some error ,like
 'Fatal error: Call to a member function connect() on a non-object in C:\xampp\htdocs\php\phpfastcache-final\phpfastcache\3.0.0\drivers\redis.php on line 78'

and my computer now has not the redis environment , but the driver fallback has been setted to 'files',why the cache  get function can't get the value ,

it is the first question form me ,in github. Nice to talk to you .

Thanks .......

from beijng ,China,

**Comment by khoaofgod** [comment]
hi, change the reddis to "files"
since your computer don't have redis installed.
