### ISSUE TITLE
Bad __set should not return an exception.

### ISSUE THREAD

**Issue by Geolim4** [khoaofgod/phpfastcache#86]
Hi :)
I notice that your magic function __set() throw a new exception if the syntax is "incorrect".

At that line:
https://github.com/khoaofgod/phpfastcache/blob/bce795d518326bc1e9755063c56cf241960d9b55/phpfastcache/3.0.0/abstract.php#L245

Some debug tools like Krumo use a "marker" to detect and avoid recursivity, and when your class is being debugged the Exception is triggered due to marker insertion, is there a way to bypass that ?

Regards,
Geo.

**Comment by khoaofgod** [comment]
@Geolim4  
Hi geo, I will make a throw new exception to error function, will update it next week.

**Comment by khoaofgod** [comment]
hey @Geolim4  can you help me custom function for throw error, I don't have time right now, if you can help, just let me know. Thanks.

**Comment by Geolim4** [comment]
I'm writing something similar as i forked your project, i will probably test it in next week as it a quick but complex improvement :)

**Comment by khoaofgod** [comment]
sure, just go ahead and improve it, I will review and merge the code. I am busy until April 12, since I have filming project todo for Easter.

**Comment by Geolim4** [comment]
Great, it let me the time to study all the possibilities.

**Comment by Geolim4** [comment]
I'm currently re-installing my project using composer, so i will not be able to give the PR so soon :/
But don't close it please, i stay tuned.

**Comment by khoaofgod** [comment]
ok, sure

**Comment by Geolim4** [comment]
I finally not found how to throw a custom class, BUT, i found a way to pass out this bug:

Does it is possible that:
```php
        if(isset($v[1]) && is_numeric($v[1])) {
            return $this->set($name,$v[0],$v[1], isset($v[2]) ? $v[2] : array() );
        } else {
            throw new Exception("Example ->$name = array('VALUE', 300);",98);
        }
```
modified to this?
```php
        if(isset($v[1]) && is_scalar($v[1])) {
            return $this->set($name,$v[0],$v[1], isset($v[2]) ? $v[2] : array() );
        } else {
            throw new Exception("Example ->$name = array('VALUE', 300);",98);
        }
```
(using is_scalar instead of is_numeric) ?

**Comment by Geolim4** [comment]
Bump :)
