### ISSUE TITLE
mkdir and recursive directory creation

### ISSUE THREAD

**Issue by ARTPROITCo** [khoaofgod/phpfastcache#90]
Hello,

mkdir has a 3 rd option
therefore, we can create a structure of subdirectories
this is useful in the driver of file cache and in other places where you create a new directories
because "securityKey" in setup can be of the form "namespace1/namespace2/..."

and yet, I noticed, checking the existence of the directory is done through "file_exists"
may be properly used "is_dir"?
../phpfastcache.php (179)
../drivers/file.php (55)

**Comment by khoaofgod** [comment]
1. I see, I will add this as a note on next version on securityKey setup.
2. For the is_dir and file_exists , same perform, nothing is faster or slower on these 2 func.

**Comment by ARTPROITCo** [comment]
> For the is_dir and file_exists , same perform, nothing is faster or slower on these 2 func.
yes of course. I was thinking about something else. but it does not matter
