### ISSUE TITLE
Possible to get all key=> value pairs that are in cache?

### ISSUE THREAD

**Issue by rohandalvi** [khoaofgod/phpfastcache#92]
I regularly update my cache so that I have to make minimal API calls. Is it possible to retrieve all key=>value pairs that are stored in cache, in case if I don't know the key to make the call $cache->get("key"); ?

Thanks

**Comment by khoaofgod** [comment]
You meant stats right? on next version you will have stats, and then it will return an array store all keys for you. April 12 - April 18 will have an update for that features. I'm working on it.

**Comment by codebucketdev** [comment]
Is this feature already implemented? Because I can't find anything like that in the docs and I would like to loop through the last keys stored in cache for statistics.

**Comment by Geolim4** [comment]
Hello,

There's no way to do that since there's no real way to retrieve stored keys.
But you can use tags to achieve that in V5 and later.

Cheers,
Georges

**Comment by codebucketdev** [comment]
Thanks for the quick response, works fine!

**Comment by Geolim4** [comment]
Referencing #494
