### ISSUE TITLE
Strange security key if HTTP_HOST starts with "w"

### ISSUE THREAD

**Issue by jensschulze** [khoaofgod/phpfastcache#95]
Hi :)

Please replace L159 in phpFastCache.php

    $securityKey = isset($_SERVER['HTTP_HOST']) ? ltrim(strtolower($_SERVER['HTTP_HOST']),"www.") : "default";

with

    $securityKey = isset($_SERVER['HTTP_HOST']) ? trim(preg_replace('/^www\./', '', strtolower($_SERVER['HTTP_HOST']))) : "default";

Because the ltrim() will replace every "w" and every "." at the beginning of the HTTP_HOST.

**Comment by khoaofgod** [comment]
Why bro, I want it only get the domain without "www." , we don't need trim, since will not space with an HTTP_HOST, and the preg_replace is slower.

**Comment by jensschulze** [comment]
I know what you want to do there, but have a look at http://php.net/manual/en/function.ltrim.php
The second argument is a character mask. That means ltrim($blah, "www.") strips all "w" and all "." from the left side of $blah. That is not what you want: "www.workexample.com" will be "orkexample.com" :)

I admit, you probably don’t need the trim, and the preg_replace is very ugly – maybe there is a faster solution.

**Comment by khoaofgod** [comment]
Woops, I just got into that function details and it's character mask for sure. So, "www.workexample.com" will be output "orkexample.com"
Maybe just use str_replace("www.","",$blabla), I will note this one, however let me take a look the whole reasone that I need $securityKey on the script and see if I have another solution.

**Comment by koenpunt** [comment]
A hint: 
```
substr($_SERVER['HTTP_HOST'], 0, 4) == 'www.'
```
